#!/bin/bash

if [ $# -ne 0 ];then
 /bin/echo 'Error: No arguments are supported.'
 exit 1;
fi

if [ "$RR_WITH_ENV" = "1" ]; then
. `rr_root`/tools/vmgr/runner/bin/rr_runme.sh  --chain_dir /home/faculty/d/davidkebo/csce-714/HTAX/work/sim/regression/htax_regress.davidkebo.24_11_24_13_05_24_3569/chain_0 --group_dir /home/faculty/d/davidkebo/csce-714/HTAX/work/sim/regression/htax_regress.davidkebo.24_11_24_13_05_24_3569/chain_0/all_test --run_id 4 --seed random --e_seed random --sv_seed random 
else
`rr_root`/tools/vmgr/runner/bin/rr_runme.sh  --chain_dir /home/faculty/d/davidkebo/csce-714/HTAX/work/sim/regression/htax_regress.davidkebo.24_11_24_13_05_24_3569/chain_0 --group_dir /home/faculty/d/davidkebo/csce-714/HTAX/work/sim/regression/htax_regress.davidkebo.24_11_24_13_05_24_3569/chain_0/all_test --run_id 4 --seed random --e_seed random --sv_seed random 
fi
